// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.1
// source: rides_service.proto

package rides

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RidesServiceClient is the client API for RidesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RidesServiceClient interface {
	UpdateRide(ctx context.Context, in *UpdateRideRequest, opts ...grpc.CallOption) (*UpdateRideResponse, error)
}

type ridesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRidesServiceClient(cc grpc.ClientConnInterface) RidesServiceClient {
	return &ridesServiceClient{cc}
}

func (c *ridesServiceClient) UpdateRide(ctx context.Context, in *UpdateRideRequest, opts ...grpc.CallOption) (*UpdateRideResponse, error) {
	out := new(UpdateRideResponse)
	err := c.cc.Invoke(ctx, "/rides.RidesService/UpdateRide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RidesServiceServer is the server API for RidesService service.
// All implementations must embed UnimplementedRidesServiceServer
// for forward compatibility
type RidesServiceServer interface {
	UpdateRide(context.Context, *UpdateRideRequest) (*UpdateRideResponse, error)
	mustEmbedUnimplementedRidesServiceServer()
}

// UnimplementedRidesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRidesServiceServer struct {
}

func (UnimplementedRidesServiceServer) UpdateRide(context.Context, *UpdateRideRequest) (*UpdateRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRide not implemented")
}
func (UnimplementedRidesServiceServer) mustEmbedUnimplementedRidesServiceServer() {}

// UnsafeRidesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RidesServiceServer will
// result in compilation errors.
type UnsafeRidesServiceServer interface {
	mustEmbedUnimplementedRidesServiceServer()
}

func RegisterRidesServiceServer(s grpc.ServiceRegistrar, srv RidesServiceServer) {
	s.RegisterService(&RidesService_ServiceDesc, srv)
}

func _RidesService_UpdateRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RidesServiceServer).UpdateRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rides.RidesService/UpdateRide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RidesServiceServer).UpdateRide(ctx, req.(*UpdateRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RidesService_ServiceDesc is the grpc.ServiceDesc for RidesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RidesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rides.RidesService",
	HandlerType: (*RidesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateRide",
			Handler:    _RidesService_UpdateRide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rides_service.proto",
}
