// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.1
// source: rides_service.proto

package rides

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Ride   *Ride  `protobuf:"bytes,2,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *UpdateRideRequest) Reset() {
	*x = UpdateRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideRequest) ProtoMessage() {}

func (x *UpdateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideRequest.ProtoReflect.Descriptor instead.
func (*UpdateRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *UpdateRideRequest) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type UpdateRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId  string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateRideResponse) Reset() {
	*x = UpdateRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRideResponse) ProtoMessage() {}

func (x *UpdateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRideResponse.ProtoReflect.Descriptor instead.
func (*UpdateRideResponse) Descriptor() ([]byte, []int) {
	return file_rides_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *UpdateRideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Ride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      string  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination string  `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Distance    float64 `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Cost        float64 `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *Ride) Reset() {
	*x = Ride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ride) ProtoMessage() {}

func (x *Ride) ProtoReflect() protoreflect.Message {
	mi := &file_rides_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ride.ProtoReflect.Descriptor instead.
func (*Ride) Descriptor() ([]byte, []int) {
	return file_rides_service_proto_rawDescGZIP(), []int{2}
}

func (x *Ride) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Ride) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Ride) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Ride) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_rides_service_proto protoreflect.FileDescriptor

var file_rides_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x69, 0x64, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x69, 0x64, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x69, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x69,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73,
	0x2e, 0x52, 0x69, 0x64, 0x65, 0x52, 0x04, 0x72, 0x69, 0x64, 0x65, 0x22, 0x47, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x69, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x70, 0x0a, 0x04, 0x52, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x32, 0x51, 0x0a, 0x0c, 0x52, 0x69, 0x64, 0x65, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x69, 0x64, 0x65, 0x12, 0x18, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x69, 0x7a, 0x2d, 0x72, 0x2f, 0x72,
	0x69, 0x64, 0x65, 0x68, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x69, 0x64, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rides_service_proto_rawDescOnce sync.Once
	file_rides_service_proto_rawDescData = file_rides_service_proto_rawDesc
)

func file_rides_service_proto_rawDescGZIP() []byte {
	file_rides_service_proto_rawDescOnce.Do(func() {
		file_rides_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rides_service_proto_rawDescData)
	})
	return file_rides_service_proto_rawDescData
}

var file_rides_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rides_service_proto_goTypes = []interface{}{
	(*UpdateRideRequest)(nil),  // 0: rides.UpdateRideRequest
	(*UpdateRideResponse)(nil), // 1: rides.UpdateRideResponse
	(*Ride)(nil),               // 2: rides.Ride
}
var file_rides_service_proto_depIdxs = []int32{
	2, // 0: rides.UpdateRideRequest.ride:type_name -> rides.Ride
	0, // 1: rides.RidesService.UpdateRide:input_type -> rides.UpdateRideRequest
	1, // 2: rides.RidesService.UpdateRide:output_type -> rides.UpdateRideResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rides_service_proto_init() }
func file_rides_service_proto_init() {
	if File_rides_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rides_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rides_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rides_service_proto_goTypes,
		DependencyIndexes: file_rides_service_proto_depIdxs,
		MessageInfos:      file_rides_service_proto_msgTypes,
	}.Build()
	File_rides_service_proto = out.File
	file_rides_service_proto_rawDesc = nil
	file_rides_service_proto_goTypes = nil
	file_rides_service_proto_depIdxs = nil
}
